### ISSUE TITLE
image folder missing

### ISSUE THREAD

**Issue by frankmaruf** [MuriungiPatrick/Bootstrap-5-portfolio-template#3]
plz add it

**Comment by MuriungiPatrick** [comment]
download all images here [https://drive.google.com/file/d/1T_CUN3s0jgYKNR-ivEwWM9jeHQ60GZi_/view?usp=sharing](url)

**Comment by nopedawn** [comment]
> download all images here [https://drive.google.com/file/d/1T_CUN3s0jgYKNR-ivEwWM9jeHQ60GZi_/view?usp=sharing](url)

where

**Comment by MuriungiPatrick** [comment]
https://drive.google.com/file/d/1T_CUN3s0jgYKNR-ivEwWM9jeHQ60GZi_/view?usp=sharing

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MuriungiPatrick** [comment]
Sorry Use this link 
https://drive.google.com/file/d/1T_CUN3s0jgYKNR-ivEwWM9jeHQ60GZi_/view?usp=sharing

**Comment by nopedawn** [comment]
Sure thank’s Sent from Mail for Windows 10 From: MuriungiSent: Sunday, June 13, 2021 6:25 PMTo: MuriungiPatrick/Bootstrap-5-portfolio-templateCc: nopedawn; CommentSubject: Re: [MuriungiPatrick/Bootstrap-5-portfolio-template] image folder missing (#3) Sorry Use this linkhttps://drive.google.com/file/d/1T_CUN3s0jgYKNR-ivEwWM9jeHQ60GZi_/view?usp=sharing—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
